apiVersion: release-notes/v2
kind: bug-fix
area: installation

releaseNotes:
  - |
    **Fixed** netlink error may not be correctly parsed, leading to `istio-cni` not properly ignoring leftover ipset.
    **Removed** CNI_NET_DIR variable from `istio-cni` configmap - it is unused
