{{- if eq .Values.provider "multus" }}
apiVersion: k8s.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: {{ template "name" . }}
  namespace: default
  labels:
    operator.istio.io/component: "Cni"
{{- end }}
