pilot:
  env:
    # 1.24 behavioral changes
    ENABLE_INBOUND_RETRY_POLICY: "false"
    EXCLUDE_UNSAFE_503_FROM_DEFAULT_RETRY: "false"
    PREFER_DESTINATIONRULE_TLS_FOR_EXTERNAL_SERVICES: "false"

meshConfig:
  defaultConfig:
    proxyMetadata:
      # 1.24 behaviour changes
      ENABLE_DEFERRED_STATS_CREATION: "false"  
