pilot:
  env:
    # 1.22 behavioral changes
    ENABLE_ENHANCED_RESOURCE_SCOPING: "false"
    ENABLE_RESOLUTION_NONE_TARGET_PORT: "false"

    # 1.24 behavioral changes
    ENABLE_INBOUND_RETRY_POLICY: "false"
    
meshConfig:
  # 1.22 behavioral changes
  defaultConfig:
    proxyMetadata:
      ISTIO_DELTA_XDS: "false"
    tracing:
      zipkin:
        address: zipkin.istio-system:9411
